### ISSUE TITLE
LV2 plugins not working with bitwig

### ISSUE THREAD

**Issue by Hedronmx** [olegkapitonov/Kapitonov-Plugins-Pack#13]
I tried using the lv2 plugins in bitwig but they cannot be loaded. Not sure if this is a problem with bitwig or not.

![Screenshot from 2020-04-18 15 21 49](https://user-images.githubusercontent.com/26935602/79672590-5a600900-8188-11ea-9948-f75c83b35f0c.png)

**Comment by sub26nico** [comment]
Sadly, Bitwig doesn't support natively lv2 plugins. You can use lv2 plugin in Bitwig with Carla-vst : 
(https://kx.studio/Applications:Carla)

**Comment by Hedronmx** [comment]
I see, Ill give it a shot! thanks

**Comment by DroWnThePoor** [comment]
> Sadly, Bitwig doesn't support natively lv2 plugins. You can use lv2 plugin in Bitwig with Carla-vst : (https://kx.studio/Applications:Carla)

Do you mean running Carla as a separate application/host? 
Because I could not get Bitwig to load/recognize the plug-in version of Carla like I can in LMMS/Reaper/Ardour/other DAWs.
I was under the assumption that Carla was available as a VST in those situations.
