### ISSUE TITLE
issue with kpp_tubeAmp

### ISSUE THREAD

**Issue by sub26nico** [olegkapitonov/Kapitonov-Plugins-Pack#17]
Hi, testing kpp plugins pack v1.2 on LibraZiK3 (based on Debian Buster) I notice an strange issue with kpp_tubeAmp : 
To reproduce : 
- Open the kpp_tubeAmp GUI
- Click on the amps profile box
- Change or not the profile amp then click on 'cancel'
- Click again on the amps profile box
In Ardour (5.12 and 6 from ardour.org and 5.12 from LibraZiK repo), it crash the host. In Carla and Jalv.select, it crash the GUI. 
Here the logs : 
- Ardour5 : 
`ardour-5.12.0: ../../../../src/cairo.c :524 : cairo_destroy:  l'assertion « CAIRO_REFERENCE_COUNT_HAS_REFERENCE (&cr->ref_count) » a échoué.
`
- In Ardour6 : 
`ardour-6.0.0: cairo.c :305 : cairo_destroy:  l'assertion « CAIRO_REFERENCE_COUNT_HAS_REFERENCE (&cr->ref_count) » a échoué.`

- In Carla : 
`carla-bridge-lv2-x11: ../../../../src/cairo.c:524: cairo_destroy: Assertion `CAIRO_REFERENCE_COUNT_HAS_REFERENCE (&cr->ref_count)' failed.`

- In Jalv.select : 
`jalv.gtk: ../../../../src/cairo.c :524 : cairo_destroy:  l'assertion « CAIRO_REFERENCE_COUNT_HAS_REFERENCE (&cr->ref_count) » a échoué.`

**Comment by olegkapitonov** [comment]
Goddamnit

Thank you very much, @sub26nico!

Fixed this, please try latest master.
I need to recreate release and binaries now...

**Comment by sub26nico** [comment]
I try asap (today)

**Comment by trebmuh** [comment]
Seems to be working now. :+1:

**Comment by olegkapitonov** [comment]
So I will prepare bugfix release like Audacity last days :)

**Comment by sub26nico** [comment]
> Seems to be working now. +1

Confirmed. no more crashes. Thanks @olegkapitonov for the quick fix and thanks @trebmuh for the package ;-).

**Comment by sub26nico** [comment]
Issue fixed, i closed here.
