### ISSUE TITLE
A very very strange bug.. (at least to my eyes!)

### ISSUE THREAD

**Issue by trebmuh** [olegkapitonov/Kapitonov-Plugins-Pack#18]
- I launch tubeamp with jalv.select (jalv.gtk) (jalv 1.6.0 from Debian Buster)
- no input/output are connected catia (so far, everything is normal)
- I play a song with VLC (and its jack output so that it appears in catia)
- VLC appears in catia and connects to the system outputs (my headphones).

(now, this is where it starts to get crazy)

- I'm connecting the VLC outputs to the KPP inputs in catia, PLEASE NOTE: KPP OUTPUTS IN CATIA ARE NOT CONNECTED...
- well... the sound still changes in my headphones, and I'll admit it's a bit of a magic trick for me

(I'm no coder but...) it's as if the modeling of the amp loaded by default is self-connecting, but the GUI buttons are not. Like there's a thread for the DSP, and another thread for the GUI, and that the DSP thread loads the amp modeling, and auto-connects to the outputs without saying or showing it.

**Comment by sub26nico** [comment]
same here

**Comment by YruamaLairba** [comment]
Same here, but it disappear when there is a second connection to the input. I suspect the plugin is modifying the data inside the input buffer. I think it's related to this http://lv2plug.in/ns/lv2core#inPlaceBroken

**Comment by olegkapitonov** [comment]
Yes, @YruamaLairba is right. tubeAmp is modifying the input buffer.

It can be easily fixed. I will try tomorrow to use jalv.select.

**Comment by trebmuh** [comment]
Nice to read.

**Comment by trebmuh** [comment]
Nice to read, let me know when I can test the fix please.

**Comment by olegkapitonov** [comment]
@trebmuh
I pushed fix to master and thirdparty-included branches

**Comment by trebmuh** [comment]
I'm confirming that it works.
Thanks @olegkapitonov !

_PS: I've updated the package in LibraZiK-3_
