### ISSUE TITLE
'make LADSPA' also builds LV2

### ISSUE THREAD

**Issue by Gimmeapill** [olegkapitonov/Kapitonov-Plugins-Pack#5]
A very minor issue spotted when trying to make split packages for LADSPA & LV2: 'make' builds only LV2 which is fine, but 'make LADSPA' builds both LADSPA & LV2 on my system. This shouldn't be the case according to the documentation.

**Comment by olegkapitonov** [comment]
Thank you for reporting this, and for pkgbuild in AUR!

I recheked makefiles, and 'make LADSPA' build only LADSPA binaries on
my system. But - 'make clean' for Distruction and Fuzz does not remove LV2 binary.
I think this causes the problem you see.

Will fix this now.

**Comment by olegkapitonov** [comment]
I pushed fix, please check

**Comment by Gimmeapill** [comment]
Thanks for the fast feedback (and the great emulations ;-))
The behavior is still weird, but I just noticed that I have probably reported the issue incorrectly: with 'make LADSPA' the lv2 folders are created, like "/usr/lib/lv2/kpp_distruction.lv2/", yet they contains only the .png & .ttl files, not the .so binaries. 
I didn't check yesterday what was actually inside the lv2 folders, so this was possibly already the case.
Anyway, I don't think I will bother pushing a package for LADSPA unless someone requests it, & I can deal with the leftovers folders in the pkgbuild, so this is really cosmetic.

**Comment by olegkapitonov** [comment]
Makefiles now only creates binary files in this folders. Both LV2 and LADSPA folders exist
before build with other files.

Is that a problem for creating packages? Can you simply purge unneeded folders in pkgbuild?
'make LADSPA' doesn't build LV2 binaries and doesn't waste build time.

**Comment by Gimmeapill** [comment]
Yes, that behavior is fine, the rest is indeed packaging duty.
Thanks for the support ;-)
