### ISSUE TITLE
Issue with kpp_tubeamp and JACK at 44100kHz samplerate.

### ISSUE THREAD

**Issue by sub26nico** [olegkapitonov/Kapitonov-Plugins-Pack#6]
kpp_tubeamp doesn't work here if Jack is configured at 44100kHz. I've tested in Ardour (5.12), Carla (2.0.0) and Qtractor (0.9.9). It's not only the host but the entire audio system which is blocked. No problem at 48kHz. I'm on LibraZiK  (Audio-oriented distro based on Debian 9), 
with KPP 1.0. Other plugins seems to works fine (except kpp_octaver but it's not the same issue and i'll open another issue for it).

**Comment by bobpatraque** [comment]
Same problem here !
I've just tried 48 kHZ, and it seems to work flawlessly... KPP amp just freeze at 441...

**Comment by olegkapitonov** [comment]
Thank you for reporting this!

sub26nico - sorry for the delay! There is a bug in 1.0 release. Please try to compile version from master,
since 1.0 release there were 10 bugfix commits. Now 44100 Hz should work fine,
and on my system all works flawlessly.

bobpatraque - are you using 1.0 version too?

**Comment by sub26nico** [comment]
I'll try as soon as possible. Gonna take a try on Debian Buster.

**Comment by bobpatraque** [comment]
I'm using the ready-to-go lv2 release, so yes, it should be the 1.0 version...
I'm not really good at compiling... 
Everytimes I've tried, it failed for a lots of reasons I do not really understand...

I'll try that maybe tomorrow, and I give you feedback ! Thanks for the reply !

**Comment by sub26nico** [comment]
@olegkapitonov , you are right, with an up to date package, this issue doesn't happens anymore. I notice another point, the 'crunch/clean' button always stay on the 'crunch' position, I don't find the way to put it on 'clean' (same with the 4 amps). Is it an issue ?

**Comment by olegkapitonov** [comment]
This is not a bug, just not implemented yet.
I will make a correction release, but I'm spending all of available time
prepairing *.tapf Profile Editor realease.

**Comment by sub26nico** [comment]
Ok, thanks. So I close here.
