### ISSUE TITLE
kpp_octaver doesn't sound like an octaver

### ISSUE THREAD

**Issue by sub26nico** [olegkapitonov/Kapitonov-Plugins-Pack#7]
I made some tests with kpp_octaver and I can't have the octaver's pedal typical sound (like with gx Detune or MDA Detune), the 'octave1' and 'octave2' sounds more as filters ('dry' knob down). 
OS: LibraZiK
KPP 1.0

**Comment by olegkapitonov** [comment]
Can you give the file with the sound you want, and with the sound you get from KPP?

kpp_octaver adds a non-distorted, clean notes one octave below the played note, and two octave below.

**Comment by sub26nico** [comment]
Thanks for the explanation. I've made a short video, with kpp_octaver and gxDetune. I can hear what kpp_octave does but i hear gxTuner have  closer sound to octaver guitar pedal. kpp_octaver sound more like filters, it's a little surprising. 

[https://www.youtube.com/watch?v=YXru3NaTGHU&feature=youtu.be](url)

**Comment by olegkapitonov** [comment]
In my plugins, the modulated sound go through heavy low-pass filters. That's the reason. I'll think about it.

**Comment by sub26nico** [comment]
As it appears it's not an issue, i close here. Last but not the least, thanks @olegkapitonov  for your works and plugins.

**Comment by sub26nico** [comment]
Hi,
just to let you know that the last version of kpp_octaver sounds really great, thanks you.

**Comment by olegkapitonov** [comment]
Thanks!
